---
name: Perform static analyses

description: Run static analysis checks on code for pull requests

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Fill default configuration files
      shell: bash
      run: python '${{ github.action_path }}/fill_configs.py' '${{ github.action_path }}/config' '${{ github.workspace }}'

      # MegaLinter
    - name: Run Megalinter
      shell: bash
      env:
        VALIDATE_ALL_CODEBASE: true
      run: |
        docker run \
          --rm \
          -v "${{ github.workspace}}:/github/workspace" \
          -v "/var/run/docker.sock:/var/run/docker.sock:rw" \
          oxsecurity/megalinter:beta

    # Upload MegaLinter artifacts
    - name: Archive production artifacts
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: MegaLinter reports
        path: |
          megalinter-reports
          mega-linter.log
