---
name: Perform static analyses

description: Run static analysis checks on code for pull requests

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Fill default configuration files
      shell: bash
      run: python '${{ github.action_path }}/fill_configs.py' '${{ github.action_path }}/config' '${{ github.workspace }}'

      # MegaLinter
    - name: Run Megalinter
      shell: bash
      env:
        VALIDATE_ALL_CODEBASE: true
      run: |
        docker run \
          --rm \
          -e GITHUB_ACTION \
          -e GITHUB_ACTION_REPOSITORY \
          -e GITHUB_ACTOR \
          -e GITHUB_API_URL \
          -e GITHUB_BASE_REF \
          -e GITHUB_EVENT_NAME \
          -e GITHUB_GRAPHQL_URL \
          -e GITHUB_HEAD_REF \
          -e GITHUB_JOB \
          -e GITHUB_REF \
          -e GITHUB_REF_NAME \
          -e GITHUB_REF_TYPE \
          -e GITHUB_REPOSITORY \
          -e GITHUB_REPOSITORY_OWNER \
          -e GITHUB_RUN_ID \
          -e GITHUB_RUN_NUMBER \
          -e GITHUB_SERVER_URL \
          -e GITHUB_SHA \
          -e GITHUB_TOKEN \
          -e GITHUB_WORKFLOW \
          -e GITHUB_WORKSPACE:/tmp/lint \
          -v "${{ github.workspace}}:/tmp/lint" \
          -v "/var/run/docker.sock:/var/run/docker.sock:rw" \
          ghcr.io/nwiltsie/megalinter-bioinformatics:beta

    # Upload MegaLinter artifacts
    - name: Archive production artifacts
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: MegaLinter reports
        path: |
          megalinter-reports
          mega-linter.log
