---
name: Perform static analyses

description: Run static analysis checks on code for pull requests

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Fill default configuration files
      shell: bash
      run: |
        pip install ruamel.yaml
        python '${{ github.action_path }}/fill_configs.py' '${{ github.action_path }}/config' '${{ github.workspace }}'

    - name: Install problem matchers
      shell: bash
      run: |
        for file in ${{ github.action_path}}/matchers/*; do
          if [ -f "$file" ]; then
            echo "::add-matcher::$(realpath "$file")"
          fi
        done

    # MegaLinter
    - name: Run Megalinter
      shell: bash
      env:
        VALIDATE_ALL_CODEBASE: true
      run: |
        docker run \
          --rm \
          -e VALIDATE_ALL_CODEBASE \
          -v "${{ github.action_path }}:/tmp/tool-static-analysis" \
          -v "${{ github.workspace}}:/tmp/lint" \
          -v "/var/run/docker.sock:/var/run/docker.sock:rw" \
          ghcr.io/nwiltsie/bl-megalinter:beta

    # Upload MegaLinter artifacts
    - name: Archive production artifacts
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: MegaLinter reports
        path: |
          megalinter-reports
          mega-linter.log
