---
name: Static analysis

description: Run static analysis checks on code for pull requests

inputs:
  docker-tag:
    description: Docker image tag to use for running checks
    default: latest
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # https://github.com/orgs/community/discussions/9049#discussioncomment-4239509
    - name: Configure image name
      run: |
          action_path="${{ github.action_path }}"
          sed -i "s/DOCKER_IMAGE_TAG/$DOCKER_IMAGE_TAG/g" "$action_path/template/action.yml"
          pwd
          ls
          tree
