---
name: Static analysis

description: Run static analysis checks on code for pull requests

inputs:
  docker-tag:
    description: Docker image tag to use for running checks
    default: latest
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # https://github.com/orgs/community/discussions/9049#discussioncomment-4239509
    - name: Configure image name
      shell: bash
      env:
        DOCKER_IMAGE_TAG: ${{ inputs.docker-tag }}
      run: |
          # There absolutely should not be an 'action.yml' file underneath the
          # .git folder, so we should be able to safely assume we won't be
          # stomping over it
          sed -e "s/DOCKER_IMAGE_TAG/$DOCKER_IMAGE_TAG/g" "$GITHUB_ACTION_PATH/template/action.yml" > ./.git/action.yml
          cat ./.git/action.yml

    - name: Run checks
      uses: ./.git
