---
ENABLE:
  - ACTION
  - BASH
  - CPP
  - GROOVY
  - JAVASCRIPT
  - JSON
  - PERL
  - PYTHON
  - R
  - YAML
GITHUB_STATUS_REPORTER: true
JSON_REPORTER: true
JSON_REPORTER_OUTPUT_DETAIL: detailed
FILTER_REGEX_EXCLUDE: (metadata.yaml)
DISABLE_LINTERS:
  - PYTHON_BANDIT
  - PYTHON_BLACK
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - PYTHON_MYPY
  - PYTHON_PYRIGHT
  - PYTHON_RUFF
DISABLE_ERRORS_LINTERS:
  - ACTION_ACTIONLINT
  - BASH_EXEC
  - BASH_SHELLCHECK
  - BASH_SHFMT
  - CPP_CLANG_FORMAT
  - CPP_CPPLINT
  - GROOVY_NPM_GROOVY_LINT
  - JSON_PRETTIER
  - JSON_V8R
