---
# @generated - This file is copied in by tool-static-analysis

BASH_SHELLCHECK_ARGUMENTS:
  - --format
  - gcc

BASH_SHFMT_ARGUMENTS:
  - -i
  - "4"

ENABLE:
  - ACTION
  - BASH
  - CPP
  - DOCKERFILE
  - GROOVY
  - JAVASCRIPT
  - JSON
  - PERL
  - PYTHON
  - R
  - UCLAHS
  - YAML

JSON_REPORTER: true

JSON_REPORTER_OUTPUT_DETAIL: detailed

FILTER_REGEX_EXCLUDE: (metadata.yaml)

DISABLE_LINTERS:
  - PYTHON_BANDIT
  - PYTHON_BLACK
  - PYTHON_FLAKE8
  - PYTHON_MYPY

DISABLE_ERRORS_LINTERS:
  - ACTION_ACTIONLINT
  - BASH_SHELLCHECK
  - DOCKERFILE_HADOLINT
  - PYTHON_ISORT
  - PYTHON_PYRIGHT
  - PYTHON_RUFF
  - UCLAHS_README_TEXT
  - YAML_V8R
  - GROOVY_NPM_GROOVY_LINT

R_LINTR_CONFIG_FILE: .lintr.R

YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: (\.github\/workflows\/)

JSON_V8R_FILTER_REGEX_INCLUDE: (\.github\/)

YAML_V8R_FILTER_REGEX_EXCLUDE: (\.mega-linter\.yml)

IGNORE_GENERATED_FILES: true

FILEIO_REPORTER: false

PYTHON_DEFAULT_STYLE: ruff

PRINT_ALPACA: false
