# @generated - This file is copied in by tool-static-analysis
---
extends: default

rules:
  line-length: disable

  # Github Action's YAML config uses 'on' as a key to trigger runs
  truthy: disable
